{- | A frog wants to cross a river that is 11 feet across

There are 10 stones in a line leading across the river, separated by 1 foot.
The frog is only ever able to jump
  one foot forward to the next stone,
  or two feet forward to the stone after the next.

In how many different ways can it jump exactly 11 feet to the other side of the river?
fib(12) = 144

f(n) = f(n-1) + f(n-2)

fib(2) = 1
fib(3) = 2
fib(4) = 3
fib(5) = 5
fib(6) = 8

Example:

n-2  ~~~~ ~~~~~~~~~ .........
n-2  ~~~~~~~~~ ~~~~ .........
n-2  ~~~~ ~~~~ ~~~~ .........
n-1  ~~~~ ~~~~ ~~~~~~~~~ ....
n-1  ~~~~~~~~~ ~~~~~~~~~ ....
n-1  ~~~~~~~~~ ~~~~ ~~~~ ....
n-1  ~~~~ ~~~~~~~~~ ~~~~ ....
n-1  ~~~~ ~~~~ ~~~~ ~~~~ ....
 
n-2  ~~~~ ~~~~ .........
n-2  ~~~~~~~~~ .........
n-1  ~~~~ ~~~~~~~~~ ....
n-1  ~~~~~~~~~ ~~~~ ....
n-1  ~~~~ ~~~~ ~~~~ ....
 
n-2  ~~~~ .........
n-1  ~~~~~~~~~ ....
n-1  ~~~~ ~~~~ ....

n-2  .........
n-1  ~~~~ ....

     ....
    _    _    _    _    _    _

-}
